/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Form;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Hacke
 */
public class KhoBia extends javax.swing.JPanel {

    /**
     * Creates new form HoaDon
     */
    public KhoBia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        khoBiaPanel = new javax.swing.JPanel();
        hoaDonPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSBiaTrongKho = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        txtTenKho_QuanLyBia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtSoLuong_Kho = new javax.swing.JTextField();
        txtTenBia_QuanLyKho = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiaChi_Kho = new javax.swing.JTextArea();
        txtMaKho_Kho = new javax.swing.JTextField();
        txtMaBia_Kho = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        btnLoadLaiTrongTongBIa = new javax.swing.JButton();
        txtKhoBiaSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelThemKho = new javax.swing.JPanel();
        labelThemKho = new javax.swing.JLabel();
        panelSuaKho = new javax.swing.JPanel();
        labelSuaKho = new javax.swing.JLabel();
        panelXoaKho = new javax.swing.JPanel();
        labelXoaKho = new javax.swing.JLabel();
        panelMoiBia = new javax.swing.JPanel();
        labelMoiKho = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinKho = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtKho = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTenKho = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblKho_TongBia = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKhoChiTiet = new javax.swing.JTable();
        txtSoLuong2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        panelThemKho2 = new javax.swing.JPanel();
        labelThemKho2 = new javax.swing.JLabel();
        panelSuaKho1 = new javax.swing.JPanel();
        labelSuaKho2 = new javax.swing.JLabel();
        panelXoaKho1 = new javax.swing.JPanel();
        labelXoaKho2 = new javax.swing.JLabel();
        panelMoiBia1 = new javax.swing.JPanel();
        labelMoiKho2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMabia2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtMaKho2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1700, 890));

        khoBiaPanel.setBackground(new java.awt.Color(255, 255, 153));

        hoaDonPanel1.setBackground(new java.awt.Color(255, 255, 255));
        hoaDonPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 5));

        tblDSBiaTrongKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên kho", "Tên bia", "Số lượng", "Makho", "MaBia", "DiaChi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSBiaTrongKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSBiaTrongKhoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDSBiaTrongKho);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Tên bia:");

        txtTenKho_QuanLyBia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenKho_QuanLyBia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKho_QuanLyBiaActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Tên kho:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Số lượng:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Địa chỉ:");

        txtSoLuong_Kho.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtTenBia_QuanLyKho.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenBia_QuanLyKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenBia_QuanLyKhoActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Mã kho:");

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Mã bia:");

        jLabel55.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel55.setText("Danh sách bia trong kho");

        txtDiaChi_Kho.setColumns(20);
        txtDiaChi_Kho.setRows(5);
        txtDiaChi_Kho.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(txtDiaChi_Kho);

        txtMaKho_Kho.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtMaBia_Kho.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel56.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel56.setText("Tìm kiếm:");

        btnLoadLaiTrongTongBIa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLoadLaiTrongTongBIa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-available-updates-24.png"))); // NOI18N
        btnLoadLaiTrongTongBIa.setText("Load lại bảng");
        btnLoadLaiTrongTongBIa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadLaiTrongTongBIaActionPerformed(evt);
            }
        });

        txtKhoBiaSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKhoBiaSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKhoBiaSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKhoBiaSearch)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnLoadLaiTrongTongBIa)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(btnLoadLaiTrongTongBIa))
                .addGap(18, 18, 18)
                .addComponent(txtKhoBiaSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout hoaDonPanel1Layout = new javax.swing.GroupLayout(hoaDonPanel1);
        hoaDonPanel1.setLayout(hoaDonPanel1Layout);
        hoaDonPanel1Layout.setHorizontalGroup(
            hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                        .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKho_Kho)
                                    .addComponent(txtMaBia_Kho, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenKho_QuanLyBia, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                        .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(txtTenBia_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        hoaDonPanel1Layout.setVerticalGroup(
            hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55)
                .addGap(15, 15, 15)
                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenKho_QuanLyBia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoLuong_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMaKho_Kho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel52)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hoaDonPanel1Layout.createSequentialGroup()
                        .addGroup(hoaDonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenBia_QuanLyKho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaBia_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 5));

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));

        panelThemKho.setBackground(new java.awt.Color(255, 255, 255));
        panelThemKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelThemKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-new-24.png"))); // NOI18N
        labelThemKho.setText("Thêm");
        labelThemKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelThemKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelThemKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelThemKhoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelThemKhoLayout = new javax.swing.GroupLayout(panelThemKho);
        panelThemKho.setLayout(panelThemKhoLayout);
        panelThemKhoLayout.setHorizontalGroup(
            panelThemKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemKhoLayout.createSequentialGroup()
                .addComponent(labelThemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelThemKhoLayout.setVerticalGroup(
            panelThemKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelThemKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelSuaKho.setBackground(new java.awt.Color(255, 255, 255));

        labelSuaKho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hacke\\OneDrive\\Máy tính\\DuAn1\\src\\icon\\icons8-pencil-30.png")); // NOI18N
        labelSuaKho.setText("Sửa");
        labelSuaKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSuaKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSuaKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSuaKhoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSuaKhoLayout = new javax.swing.GroupLayout(panelSuaKho);
        panelSuaKho.setLayout(panelSuaKhoLayout);
        panelSuaKhoLayout.setHorizontalGroup(
            panelSuaKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuaKhoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(labelSuaKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuaKhoLayout.setVerticalGroup(
            panelSuaKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSuaKho, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        panelXoaKho.setBackground(new java.awt.Color(255, 255, 255));
        panelXoaKho.setMaximumSize(new java.awt.Dimension(78, 48));
        panelXoaKho.setMinimumSize(new java.awt.Dimension(78, 48));
        panelXoaKho.setPreferredSize(new java.awt.Dimension(112, 22));

        labelXoaKho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hacke\\OneDrive\\Máy tính\\DuAn1\\src\\icon\\icons8-trash-24.png")); // NOI18N
        labelXoaKho.setText(" Xóa");
        labelXoaKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelXoaKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelXoaKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelXoaKhoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelXoaKhoLayout = new javax.swing.GroupLayout(panelXoaKho);
        panelXoaKho.setLayout(panelXoaKhoLayout);
        panelXoaKhoLayout.setHorizontalGroup(
            panelXoaKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXoaKho, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        panelXoaKhoLayout.setVerticalGroup(
            panelXoaKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXoaKho, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        panelMoiBia.setBackground(new java.awt.Color(255, 255, 255));

        labelMoiKho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hacke\\OneDrive\\Máy tính\\DuAn1\\src\\icon\\icons8-renew-24.png")); // NOI18N
        labelMoiKho.setText("Làm mới");
        labelMoiKho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelMoiKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMoiKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMoiKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMoiKhoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMoiBiaLayout = new javax.swing.GroupLayout(panelMoiBia);
        panelMoiBia.setLayout(panelMoiBiaLayout);
        panelMoiBiaLayout.setHorizontalGroup(
            panelMoiBiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMoiKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        panelMoiBiaLayout.setVerticalGroup(
            panelMoiBiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMoiKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelThemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(panelXoaKho, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSuaKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelMoiBia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelThemKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSuaKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelXoaKho, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(panelMoiBia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tblThongTinKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã kho", "Địa chỉ", "Tên kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTinKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinKhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTinKho);

        jLabel5.setText("Mã kho:");

        jLabel17.setText("Tên kho:");

        jLabel21.setText("Địa chỉ:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtTenKho)
                            .addComponent(txtKho)
                            .addComponent(jLabel21)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtKho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thông tin kho", jPanel3);

        tblKho_TongBia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kho", "Tổng sản phẩm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblKho_TongBia);

        tblKhoChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Mã kho", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoChiTietMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblKhoChiTiet);

        jPanel11.setBackground(new java.awt.Color(51, 51, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));

        panelThemKho2.setBackground(new java.awt.Color(255, 255, 255));
        panelThemKho2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelThemKho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-new-24.png"))); // NOI18N
        labelThemKho2.setText("Thêm");
        labelThemKho2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelThemKho2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelThemKho2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelThemKho2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelThemKho2Layout = new javax.swing.GroupLayout(panelThemKho2);
        panelThemKho2.setLayout(panelThemKho2Layout);
        panelThemKho2Layout.setHorizontalGroup(
            panelThemKho2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThemKho2Layout.createSequentialGroup()
                .addComponent(labelThemKho2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelThemKho2Layout.setVerticalGroup(
            panelThemKho2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelThemKho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelSuaKho1.setBackground(new java.awt.Color(255, 255, 255));

        labelSuaKho2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hacke\\OneDrive\\Máy tính\\DuAn1\\src\\icon\\icons8-pencil-30.png")); // NOI18N
        labelSuaKho2.setText("Sửa");
        labelSuaKho2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSuaKho2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSuaKho2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSuaKho2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSuaKho1Layout = new javax.swing.GroupLayout(panelSuaKho1);
        panelSuaKho1.setLayout(panelSuaKho1Layout);
        panelSuaKho1Layout.setHorizontalGroup(
            panelSuaKho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuaKho1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(labelSuaKho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuaKho1Layout.setVerticalGroup(
            panelSuaKho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSuaKho2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        panelXoaKho1.setBackground(new java.awt.Color(255, 255, 255));
        panelXoaKho1.setMaximumSize(new java.awt.Dimension(78, 48));
        panelXoaKho1.setMinimumSize(new java.awt.Dimension(78, 48));
        panelXoaKho1.setPreferredSize(new java.awt.Dimension(112, 22));

        labelXoaKho2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hacke\\OneDrive\\Máy tính\\DuAn1\\src\\icon\\icons8-trash-24.png")); // NOI18N
        labelXoaKho2.setText(" Xóa");
        labelXoaKho2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelXoaKho2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelXoaKho2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelXoaKho2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelXoaKho1Layout = new javax.swing.GroupLayout(panelXoaKho1);
        panelXoaKho1.setLayout(panelXoaKho1Layout);
        panelXoaKho1Layout.setHorizontalGroup(
            panelXoaKho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXoaKho2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        panelXoaKho1Layout.setVerticalGroup(
            panelXoaKho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelXoaKho2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        panelMoiBia1.setBackground(new java.awt.Color(255, 255, 255));

        labelMoiKho2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hacke\\OneDrive\\Máy tính\\DuAn1\\src\\icon\\icons8-renew-24.png")); // NOI18N
        labelMoiKho2.setText("Làm mới");
        labelMoiKho2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelMoiKho2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMoiKho2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMoiKho2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMoiKho2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMoiBia1Layout = new javax.swing.GroupLayout(panelMoiBia1);
        panelMoiBia1.setLayout(panelMoiBia1Layout);
        panelMoiBia1Layout.setHorizontalGroup(
            panelMoiBia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMoiKho2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        panelMoiBia1Layout.setVerticalGroup(
            panelMoiBia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMoiKho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelThemKho2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(panelXoaKho1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSuaKho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelMoiBia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelThemKho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSuaKho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelXoaKho1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(panelMoiBia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel22.setText(" Mã bia:");

        jLabel23.setText("Mã kho:");

        jLabel24.setText("Số lương:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txtMaKho2)
                            .addComponent(txtMabia2)
                            .addComponent(jLabel24)
                            .addComponent(txtSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtMabia2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKho2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tổng sản phẩm từng kho", jPanel7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jLabel54.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(204, 102, 0));
        jLabel54.setText("Quản Lý Kho Bia");

        javax.swing.GroupLayout khoBiaPanelLayout = new javax.swing.GroupLayout(khoBiaPanel);
        khoBiaPanel.setLayout(khoBiaPanelLayout);
        khoBiaPanelLayout.setHorizontalGroup(
            khoBiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoBiaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hoaDonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3286, 3286, 3286))
            .addGroup(khoBiaPanelLayout.createSequentialGroup()
                .addGap(628, 628, 628)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khoBiaPanelLayout.setVerticalGroup(
            khoBiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, khoBiaPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel54)
                .addGap(41, 41, 41)
                .addGroup(khoBiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hoaDonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(khoBiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(khoBiaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSBiaTrongKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSBiaTrongKhoMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblDSBiaTrongKho.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Lỗi", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtMaKho_Kho.setText(tblDSBiaTrongKho.getModel().getValueAt(selectedRow, 3).toString());
        txtTenKho_QuanLyBia.setText(tblDSBiaTrongKho.getModel().getValueAt(selectedRow, 0).toString());

        txtMaBia_Kho.setText(tblDSBiaTrongKho.getModel().getValueAt(selectedRow, 4).toString());
        txtTenBia_QuanLyKho.setText(tblDSBiaTrongKho.getModel().getValueAt(selectedRow, 1).toString());
        txtSoLuong_Kho.setText(tblDSBiaTrongKho.getModel().getValueAt(selectedRow, 2).toString());
        txtDiaChi_Kho.setText(tblDSBiaTrongKho.getModel().getValueAt(selectedRow, 5).toString());

    }//GEN-LAST:event_tblDSBiaTrongKhoMouseClicked

    private void txtTenKho_QuanLyBiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKho_QuanLyBiaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTenKho_QuanLyBiaActionPerformed

    private void txtTenBia_QuanLyKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenBia_QuanLyKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenBia_QuanLyKhoActionPerformed

    private void btnLoadLaiTrongTongBIaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadLaiTrongTongBIaActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_btnLoadLaiTrongTongBIaActionPerformed

    private void txtKhoBiaSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhoBiaSearchKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtKhoBiaSearchKeyPressed

    private void txtKhoBiaSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhoBiaSearchKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtKhoBiaSearchKeyTyped

    private void labelThemKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThemKhoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_labelThemKhoMouseClicked

    private void labelThemKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThemKhoMouseEntered
        // TODO add your handling code here:
        labelThemKho.setForeground(Color.red);
    }//GEN-LAST:event_labelThemKhoMouseEntered

    private void labelThemKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThemKhoMouseExited
        // TODO add your handling code here:
        labelThemKho.setForeground(Color.black);
    }//GEN-LAST:event_labelThemKhoMouseExited

    private void labelSuaKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSuaKhoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_labelSuaKhoMouseClicked

    private void labelSuaKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSuaKhoMouseEntered
        // TODO add your handling code here:
        labelSuaKho.setForeground(Color.red);
    }//GEN-LAST:event_labelSuaKhoMouseEntered

    private void labelSuaKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSuaKhoMouseExited
        // TODO add your handling code here:
        labelSuaKho.setForeground(Color.black);
    }//GEN-LAST:event_labelSuaKhoMouseExited

    private void labelXoaKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXoaKhoMouseClicked
        // TODO add your handling code here:
        String selectedMa = txtKho.getText();

        
    }//GEN-LAST:event_labelXoaKhoMouseClicked

    private void labelXoaKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXoaKhoMouseEntered
        // TODO add your handling code here:
        labelXoaKho.setForeground(Color.red);
    }//GEN-LAST:event_labelXoaKhoMouseEntered

    private void labelXoaKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXoaKhoMouseExited
        // TODO add your handling code here:
        labelXoaKho.setForeground(Color.black);
    }//GEN-LAST:event_labelXoaKhoMouseExited

    private void labelMoiKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMoiKhoMouseClicked
        // TODO add your handling code here:
        txtKho.setText("");
        txtTenKho.setText("");

        txtDiaChi.setText("");
    }//GEN-LAST:event_labelMoiKhoMouseClicked

    private void labelMoiKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMoiKhoMouseEntered
        // TODO add your handling code here:
        labelMoiKho.setForeground(Color.red);
    }//GEN-LAST:event_labelMoiKhoMouseEntered

    private void labelMoiKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMoiKhoMouseExited
        // TODO add your handling code here:
        labelMoiKho.setForeground(Color.black);
    }//GEN-LAST:event_labelMoiKhoMouseExited

    private void tblThongTinKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinKhoMouseClicked
        // TODO add your handling code here:

        int selectedRow = tblThongTinKho.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Lỗi", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtKho.setText(tblThongTinKho.getValueAt(selectedRow, 0).toString());
        txtTenKho.setText(tblThongTinKho.getValueAt(selectedRow, 2).toString());

        txtDiaChi.setText(tblThongTinKho.getValueAt(selectedRow, 1).toString());

    }//GEN-LAST:event_tblThongTinKhoMouseClicked

    private void tblKhoChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoChiTietMouseClicked
        // TODO add your handling code here:

        int selectedRow = tblKhoChiTiet.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Lỗi", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtMabia2.setText(tblKhoChiTiet.getValueAt(selectedRow, 0).toString());
        txtMaKho2.setText(tblKhoChiTiet.getValueAt(selectedRow, 1).toString());

        txtSoLuong2.setText(tblKhoChiTiet.getValueAt(selectedRow, 2).toString());

    }//GEN-LAST:event_tblKhoChiTietMouseClicked

    private void labelThemKho2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThemKho2MouseClicked
        // TODO add your handling code here:

        

    }//GEN-LAST:event_labelThemKho2MouseClicked

    private void labelThemKho2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThemKho2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelThemKho2MouseEntered

    private void labelThemKho2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelThemKho2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelThemKho2MouseExited

    private void labelSuaKho2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSuaKho2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSuaKho2MouseClicked

    private void labelSuaKho2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSuaKho2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSuaKho2MouseEntered

    private void labelSuaKho2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSuaKho2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSuaKho2MouseExited

    private void labelXoaKho2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXoaKho2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelXoaKho2MouseClicked

    private void labelXoaKho2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXoaKho2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelXoaKho2MouseEntered

    private void labelXoaKho2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelXoaKho2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelXoaKho2MouseExited

    private void labelMoiKho2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMoiKho2MouseClicked
        // TODO add your handling code here:
        txtMabia2.setText("");
        txtMaKho2.setText("");
        txtSoLuong2.setText("");
    }//GEN-LAST:event_labelMoiKho2MouseClicked

    private void labelMoiKho2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMoiKho2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMoiKho2MouseEntered

    private void labelMoiKho2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMoiKho2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMoiKho2MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadLaiTrongTongBIa;
    private javax.swing.JPanel hoaDonPanel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel khoBiaPanel;
    private javax.swing.JLabel labelMoiKho;
    private javax.swing.JLabel labelMoiKho2;
    private javax.swing.JLabel labelSuaKho;
    private javax.swing.JLabel labelSuaKho2;
    private javax.swing.JLabel labelThemKho;
    private javax.swing.JLabel labelThemKho2;
    private javax.swing.JLabel labelXoaKho;
    private javax.swing.JLabel labelXoaKho2;
    private javax.swing.JPanel panelMoiBia;
    private javax.swing.JPanel panelMoiBia1;
    private javax.swing.JPanel panelSuaKho;
    private javax.swing.JPanel panelSuaKho1;
    private javax.swing.JPanel panelThemKho;
    private javax.swing.JPanel panelThemKho2;
    private javax.swing.JPanel panelXoaKho;
    private javax.swing.JPanel panelXoaKho1;
    private javax.swing.JTable tblDSBiaTrongKho;
    private javax.swing.JTable tblKhoChiTiet;
    private javax.swing.JTable tblKho_TongBia;
    private javax.swing.JTable tblThongTinKho;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextArea txtDiaChi_Kho;
    private javax.swing.JTextField txtKho;
    private javax.swing.JTextField txtKhoBiaSearch;
    private javax.swing.JTextField txtMaBia_Kho;
    private javax.swing.JTextField txtMaKho2;
    private javax.swing.JTextField txtMaKho_Kho;
    private javax.swing.JTextField txtMabia2;
    private javax.swing.JTextField txtSoLuong2;
    private javax.swing.JTextField txtSoLuong_Kho;
    private javax.swing.JTextField txtTenBia_QuanLyKho;
    private javax.swing.JTextField txtTenKho;
    private javax.swing.JTextField txtTenKho_QuanLyBia;
    // End of variables declaration//GEN-END:variables
}
